apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: messages
  labels:
    strimzi.io/cluster: chatbot
    app: chatbot-kafka
spec:
  partitions: 1
  replicas: 1
  topicName: messages
  config:
    retention.ms: 7200000
