apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/starburst-enterprise-helm-operator-rhmp.openshift-operators: ''
  name: starburst-enterprise-helm-operator-rhmp
  namespace: openshift-operators
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: starburst-enterprise-helm-operator-rhmp
  source: redhat-marketplace
  sourceNamespace: openshift-marketplace
  startingCSV: starburst-enterprise-helm-operator.v380.3.2